// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_t-9o3Qww0Ukf9Cvh6I2UiYbCpsE-NIk',
    appId: '1:804682884313:web:fa187c1788fb76ba858ac8',
    messagingSenderId: '804682884313',
    projectId: 'flutter-chat-app-4af88',
    authDomain: 'flutter-chat-app-4af88.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4af88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeIX1HnjxP5vfcMQz1iJdhXzxW25MeQZk',
    appId: '1:804682884313:android:4905f74db7766c3f858ac8',
    messagingSenderId: '804682884313',
    projectId: 'flutter-chat-app-4af88',
    storageBucket: 'flutter-chat-app-4af88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTvYWliqqW8myaZtogYhCZnmu3BelZgLM',
    appId: '1:804682884313:ios:3e7484f0f9b099f0858ac8',
    messagingSenderId: '804682884313',
    projectId: 'flutter-chat-app-4af88',
    storageBucket: 'flutter-chat-app-4af88.appspot.com',
    iosClientId: '804682884313-dj60a3gs1sslv7aiskar49inrd9157do.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTvYWliqqW8myaZtogYhCZnmu3BelZgLM',
    appId: '1:804682884313:ios:3e7484f0f9b099f0858ac8',
    messagingSenderId: '804682884313',
    projectId: 'flutter-chat-app-4af88',
    storageBucket: 'flutter-chat-app-4af88.appspot.com',
    iosClientId: '804682884313-dj60a3gs1sslv7aiskar49inrd9157do.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
